const projects=[
{id:"01",title:"Multi-Agent AI Data Analyst",description:"Full-stack data analytics platform for CSV analysis, visualization and AI-generated insights, with ML workflows and automated PDF reporting.",tech:["Python","FastAPI","React","Plotly","Gemini"],categories:["AI","Data Analytics"],featured:true,github:"https://github.com/kavyyyaaa/Multi-Agent-AI-Data-Analyst",caseStudy:true,signal:"DATA → AGENTS → INSIGHT → REPORT",kicker:"MULTI-AGENT SYSTEM",metrics:[["AGENTS","06"],["INPUT","CSV"],["OUTPUT","PDF"],["MODE","AI"]]},
{id:"02",title:"ForgePredict AI",description:"F1-inspired predictive maintenance platform for industrial assets with real-time telemetry, failure prediction and Remaining Useful Life estimation.",tech:["Python","XGBoost","Dash","Plotly","Scikit-learn"],categories:["Machine Learning","Predictive Maintenance"],featured:true,github:"https://github.com/kavyyyaaa/ForgePredict-AI",caseStudy:true,signal:"TELEMETRY → ANOMALY → RUL → ACTION",kicker:"PREDICTIVE MAINTENANCE",metrics:[["MODEL","XGBOOST"],["OUTPUT","RUL"],["INPUT","SENSORS"],["MODE","LIVE"]]},
{id:"03",title:"MarketMind",description:"Stock forecasting and risk analytics platform combining machine learning forecasts, technical indicators and interactive dashboards.",tech:["Python","Prophet","XGBoost","Flask","Plotly"],categories:["Machine Learning","Data Analytics"],featured:true,github:"https://github.com/kavyyyaaa/Marketmind",caseStudy:true,signal:"MARKET DATA → FORECAST → RISK → DECISION",kicker:"FORECAST + RISK",metrics:[["FORECAST","ENSEMBLE"],["RISK","VaR"],["SIGNAL","RSI"],["MODE","AUDIT"]]},
{id:"04",title:"VisionSearch",description:"AI-powered visual product search engine using image embeddings and similarity search to find visually similar products.",tech:["Python","ResNet-50","FAISS","OpenCV","Flask"],categories:["Computer Vision","AI"],featured:true,github:"https://github.com/kavyyyaaa/VisionSearch",caseStudy:true,signal:"IMAGE → EMBEDDING → FAISS → RESULTS",kicker:"VISUAL RETRIEVAL",metrics:[["EMBED","2048-D"],["SEARCH","FAISS"],["VERIFY","ORB"],["MODE","VISION"]]},
{id:"05",title:"DRI Kiln Thermal Analytics",description:"Industrial thermal analytics work focused on kiln temperature data, monitoring and predictive-maintenance workflows.",tech:["Python","LSTM","Plotly","Scikit-learn"],categories:["Predictive Maintenance","Machine Learning"],github:"https://github.com/kavyyyaaa/DRI-Kiln-Thermal-Analytics",signal:"TEMPERATURE → PATTERN → ALERT",kicker:"THERMAL ANALYTICS",metrics:[["INPUT","TEMP"],["MODEL","LSTM"],["VIEW","PLOTLY"],["MODE","MONITOR"]]},
{id:"06",title:"AI-Based Logo Detection & Obfuscation",description:"Computer-vision research work around brand/logo detection and obfuscation in videos.",tech:["Computer Vision","Deep Learning"],categories:["Computer Vision","AI"],github:"https://github.com/kavyyyaaa/logo_detection_obfuscation",signal:"VIDEO → DETECT → OBFUSCATE",kicker:"COMPUTER VISION",metrics:[["INPUT","VIDEO"],["TASK","DETECT"],["OUTPUT","MASK"],["MODE","VISION"]]},
{id:"07",title:"AI Research Assistant",description:"RAG-based PDF question-answering assistant using Google Gemini, LangChain and FAISS for document-grounded answers.",tech:["Python","Gemini","LangChain","FAISS"],categories:["AI"],github:"https://github.com/kavyyyaaa/AI-Research-Assistant",signal:"PDF → EMBED → RETRIEVE → ANSWER",kicker:"RAG SYSTEM",metrics:[["INPUT","PDF"],["RETRIEVE","FAISS"],["LLM","GEMINI"],["MODE","RAG"]]},
{id:"08",title:"Customer Segmentation Project",description:"Customer analytics project focused on segmenting customers into meaningful groups for data-driven business insights.",tech:["Python","Pandas","Scikit-learn"],categories:["Data Analytics","Machine Learning"],github:"https://github.com/kavyyyaaa/Customer-Segmentation-Project",signal:"CUSTOMERS → FEATURES → SEGMENTS",kicker:"CUSTOMER ANALYTICS",metrics:[["INPUT","CUSTOMERS"],["FEATURES","DATA"],["MODEL","CLUSTER"],["MODE","ANALYTICS"]]}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const intro=$('#introScreen');
function closeIntro(){intro?.classList.add('hidden');try{sessionStorage.setItem('kavyaaIntroSeen','1')}catch(e){}}
try{if(sessionStorage.getItem('kavyaaIntroSeen')==='1')intro?.classList.add('hidden')}catch(e){}
$('#enterPortfolio')?.addEventListener('click',closeIntro);$('#skipIntro')?.addEventListener('click',closeIntro);
(function(){const live=$('#introLiveText'),sys=$('#introSystemText'),pct=$('#introPercent'),bar=$('#introBar'),clock=$('#introClock');if(!live)return;const phrases=['DATA SYSTEMS','MODEL PIPELINES','VISUAL SIGNALS','AI WORKFLOWS','INSIGHT LAYERS'],systems=['INITIALIZING','MAPPING PROJECTS','LOADING SYSTEMS','CONNECTING SIGNALS','READY'];let n=0,v=0;const update=()=>{live.textContent=phrases[n%phrases.length];sys.textContent=systems[n%systems.length];n++};update();setInterval(update,1500);const tick=()=>{v=Math.min(100,v+1);pct.textContent=String(v).padStart(2,'0')+'%';bar.style.width=v+'%';if(v<100)setTimeout(tick,24)};tick();const clockTick=()=>{const d=new Date();clock.textContent=[d.getHours(),d.getMinutes()].map(x=>String(x).padStart(2,'0')).join(':')};clockTick();setInterval(clockTick,1000)})();
const revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(e=>revealObserver.observe(e));
const nav=$('.nav'),menu=$('.menu-btn');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const list=$('#labList'),stage=$('#labStage'),title=$('#labTitle'),desc=$('#labDescription'),kicker=$('#labKicker'),tech=$('#labTech'),links=$('#labLinks'),idx=$('#labIndex'),cat=$('#labCategory'),sig=$('#labSignal'),stack=$('#labStack');let active=0;
function linksFor(p){return `<a href="${p.github}" target="_blank" rel="noreferrer">GitHub ↗</a>${p.caseStudy?`<a href="project.html?id=${p.id}">Case study ↗</a>`:''}`}
function renderStage(p){const chips=p.metrics.map((m,i)=>`<div class="metric-chip chip${i+1}">${m[0]}<strong>${m[1]}</strong></div>`).join('');stage.innerHTML=`<div class="visual-core"><i></i><strong>${p.title.split(' ').slice(0,2).join(' ')}</strong></div><div class="flow">${p.signal.split(' → ').map((x,i)=>`<span>${x}</span>${i<p.signal.split(' → ').length-1?'<b>→</b>':''}`).join('')}</div>${chips}`}
function activate(i){active=i;const p=projects[i];list.querySelectorAll('button').forEach((b,j)=>b.classList.toggle('active',j===i));idx.textContent=`${p.id} / 08`;cat.textContent=p.categories[0];title.textContent=p.title;desc.textContent=p.description;kicker.textContent=p.kicker;tech.innerHTML=p.tech.map(t=>`<span>${t}</span>`).join('');links.innerHTML=linksFor(p);sig.textContent=`SIGNAL / ${p.signal}`;stack.textContent=p.tech.slice(0,3).join(' · ').toUpperCase();renderStage(p)}
list.innerHTML=projects.map((p,i)=>`<button type="button" data-i="${i}"><span>${p.id}</span><strong>${p.title}</strong></button>`).join('');list.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>activate(+b.dataset.i)));activate(0);
const all=$('#all-projects'),filters=$('#filters');const more=()=>projects.filter(p=>!p.featured);const cats=['All',...new Set(more().flatMap(p=>p.categories))];filters.innerHTML=cats.map((c,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${c}">${c}</button>`).join('');function renderMore(filter='All'){all.innerHTML=more().filter(p=>filter==='All'||p.categories.includes(filter)).map(p=>`<article class="mini-project reveal"><span class="kicker">${p.id}</span><h4>${p.title}</h4><p>${p.description}</p><div class="tech-list">${p.tech.slice(0,4).map(t=>`<span>${t}</span>`).join('')}</div><div class="lab-links">${linksFor(p)}</div></article>`).join('');all.querySelectorAll('.reveal').forEach(e=>revealObserver.observe(e))}renderMore();filters.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{filters.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMore(b.dataset.filter)}));
const steps=$$('.story-step'),storyTitle=$('#storyTitleText'),storyText=$('#storyText'),storyIndex=$('#storyIndex'),meter=$('#storyMeter');const titleState={v:0},textState={v:0};function type(el,text,speed,state){const run=++state.v;el.textContent='';let i=0;const go=()=>{if(run!==state.v)return;el.textContent=text.slice(0,++i);if(i<text.length)setTimeout(go,speed)};go()}function storyActivate(s){steps.forEach(x=>x.classList.toggle('active',x===s));storyIndex.textContent=s.dataset.index;meter.style.width=(parseInt(s.dataset.index)*33.333)+'%';type(storyTitle,s.dataset.title,48,titleState);type(storyText,s.dataset.text,10,textState)}const so=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)storyActivate(e.target)}),{rootMargin:'-38% 0px -42% 0px',threshold:0});steps.forEach(s=>so.observe(s));storyActivate(steps[0]);
let ticking=false;window.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;$('#scrollProgress').style.width=(max>0?scrollY/max*100:0)+'%';ticking=false})},{passive:true});
