const projects=[
['01','Multi-Agent AI Data Analyst','Full-stack data analytics platform for CSV analysis, visualization, AI-generated insights and PDF reporting.',['Python','FastAPI','React','Plotly','Gemini'],'AI / DATA','https://github.com/kavyyyaaa/Multi-Agent-AI-Data-Analyst','agents'],
['02','ForgePredict AI','Predictive maintenance platform with telemetry, failure prediction, Remaining Useful Life and explainable analytics.',['Python','XGBoost','Dash','SHAP','Plotly'],'ML / INDUSTRIAL','https://github.com/kavyyyaaa/ForgePredict-AI','forge'],
['03','MarketMind','Stock forecasting and risk analytics combining ensemble forecasts, technical indicators and interactive dashboards.',['Python','Prophet','XGBoost','Flask','Plotly'],'FORECAST / RISK','https://github.com/kavyyyaaa/Marketmind','market'],
['04','VisionSearch','Visual product search using ResNet-50 embeddings, FAISS similarity search and OpenCV verification.',['Python','ResNet-50','FAISS','OpenCV','Flask'],'VISION / RETRIEVAL','https://github.com/kavyyyaaa/VisionSearch','vision'],
['05','DRI Kiln Thermal Analytics','Industrial thermal analytics focused on kiln temperature data, monitoring and predictive maintenance.',['Python','LSTM','Plotly','Scikit-learn'],'INDUSTRIAL / ML','https://github.com/kavyyyaaa/DRI-Kiln-Thermal-Analytics','thermal'],
['06','Logo Detection & Obfuscation','Computer-vision research work around brand and logo detection and obfuscation in videos.',['Computer Vision','Deep Learning'],'VISION / RESEARCH','https://github.com/kavyyyaaa/logo_detection_obfuscation','logo'],
['07','AI Research Assistant','RAG-based PDF question answering using Gemini, LangChain and FAISS.',['Python','Gemini','LangChain','FAISS'],'RAG / LLM','https://github.com/kavyyyaaa/AI-Research-Assistant','rag'],
['08','Customer Segmentation Project','Customer analytics project focused on meaningful groups for data-driven business insights.',['Python','Pandas','Scikit-learn'],'ANALYTICS / ML','https://github.com/kavyyyaaa/Customer-Segmentation-Project','segment']
];
const $=s=>document.querySelector(s),list=$('#projectList');
projects.forEach((p,i)=>{const a=document.createElement('a');a.className='project-item'+(i===0?' active':'');a.href='#work';a.dataset.i=i;a.innerHTML=`<span>${p[0]}</span><b>${p[1]}</b><small>${i<4?'FEATURED':'SYSTEM'}</small><i>↗</i>`;list.appendChild(a);});
const viz=$('#viz'), title=$('#previewTitle'),desc=$('#previewDesc'),tags=$('#previewTags'),github=$('#github'),no=$('#previewNo'),type=$('#previewType');
function draw(type){if(type==='agents')return `<div class="node" style="left:8%;top:38%">CSV / DATA</div><div class="node" style="left:39%;top:18%">ANALYSIS AGENT</div><div class="node" style="left:39%;top:42%">INSIGHT AGENT</div><div class="node" style="left:39%;top:66%">REPORT AGENT</div><div class="node" style="right:7%;top:42%">DECISION</div><div class="line" style="width:150px;left:18%;top:50%"></div><div class="line" style="width:120px;left:58%;top:50%"></div><div class="pulse" style="left:34%;top:49%"></div>`;
if(type==='forge')return `<div class="chart"><svg viewBox="0 0 500 190" preserveAspectRatio="none"><polyline points="0,150 70,135 120,142 170,80 230,105 285,55 350,82 410,35 500,58" fill="none" stroke="#aeb0aa" stroke-width="2"/><polyline points="0,165 100,158 200,160 300,150 400,145 500,142" fill="none" stroke="#41423e" stroke-width="2"/></svg></div><div class="node" style="right:7%;top:12%">RUL / 18.4h</div><div class="pulse" style="left:57%;top:32%"></div>`;
if(type==='market')return `<div class="chart"><svg viewBox="0 0 500 190" preserveAspectRatio="none"><polyline points="0,150 50,120 95,130 145,95 190,110 240,62 285,85 330,48 380,72 430,34 500,55" fill="none" stroke="#aeb0aa" stroke-width="2"/><polyline points="380,72 430,34 500,18" fill="none" stroke="#9ab7ff" stroke-width="2" stroke-dasharray="5 5"/></svg></div><div class="node" style="left:7%;top:12%">VaR / 95%</div>`;
if(type==='vision')return `<div class="thumb" style="left:9%;top:37%"></div><div class="node" style="left:38%;top:38%">2048-D EMBEDDING</div><div class="node" style="right:8%;top:28%">FAISS / TOP-K</div><div class="line" style="width:150px;left:22%;top:51%"></div><div class="line" style="width:140px;left:62%;top:48%"></div><div class="pulse" style="left:35%;top:49%"></div>`;
return `<div class="node" style="left:12%;top:42%">INPUT</div><div class="node" style="left:43%;top:42%">MODEL</div><div class="node" style="right:10%;top:42%">OUTPUT</div><div class="line" style="width:145px;left:22%;top:50%"></div><div class="line" style="width:145px;left:55%;top:50%"></div>`}
function select(i){const p=projects[i];document.querySelectorAll('.project-item').forEach((x,j)=>x.classList.toggle('active',j===i));no.textContent=p[0]+' / 08';type.textContent=p[4];title.textContent=p[1];desc.textContent=p[2];github.href=p[5];tags.innerHTML=p[3].map(x=>`<span>${x}</span>`).join('');viz.innerHTML=draw(p[6]);}
select(0);document.querySelectorAll('.project-item').forEach(a=>a.addEventListener('mouseenter',()=>select(+a.dataset.i)));document.querySelectorAll('.project-item').forEach(a=>a.addEventListener('click',()=>select(+a.dataset.i)));
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('on')),{threshold:.12});document.querySelectorAll('.section-intro,.exp-row,.tool-grid,.archive,.cert-list,.about,.contact,.hero-grid').forEach(x=>{x.classList.add('reveal');io.observe(x)});
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#scrollDot').style.top=(scrollY/h*100)+'%';});
const cur=$('#cursor');addEventListener('pointermove',e=>{if(innerWidth>900){cur.style.left=e.clientX+'px';cur.style.top=e.clientY+'px'}});
