const projects=[
{id:"01",title:"Multi-Agent AI Data Analyst",description:"Full-stack data analytics platform for CSV analysis, visualization and AI-generated insights, with ML workflows and automated PDF reporting.",tech:["Python","FastAPI","React","Plotly","Gemini"],categories:["AI","Data Analytics"],featured:true,github:"https://github.com/kavyyyaaa/Multi-Agent-AI-Data-Analyst",caseStudy:true},
{id:"02",title:"ForgePredict AI",description:"F1-inspired predictive maintenance platform for industrial assets with real-time telemetry, failure prediction and Remaining Useful Life estimation.",tech:["Python","XGBoost","Dash","Plotly","Scikit-learn"],categories:["Machine Learning","Predictive Maintenance"],featured:true,github:"https://github.com/kavyyyaaa/ForgePredict-AI",caseStudy:true},
{id:"03",title:"MarketMind",description:"Stock forecasting and risk analytics platform combining machine learning forecasts, technical indicators and interactive dashboards.",tech:["Python","Prophet","XGBoost","Flask","Plotly"],categories:["Machine Learning","Data Analytics"],featured:true,github:"https://github.com/kavyyyaaa/Marketmind",caseStudy:true},
{id:"04",title:"VisionSearch",description:"AI-powered visual product search engine using image embeddings and similarity search to find visually similar products.",tech:["Python","ResNet-50","FAISS","OpenCV","Flask"],categories:["Computer Vision","AI"],featured:true,github:"https://github.com/kavyyyaaa/VisionSearch",caseStudy:true},
{id:"05",title:"DRI Kiln Thermal Analytics",description:"Industrial thermal analytics work focused on kiln temperature data, monitoring and predictive-maintenance workflows.",tech:["Python","LSTM","Plotly","Scikit-learn"],categories:["Predictive Maintenance","Machine Learning"],github:"https://github.com/kavyyyaaa/DRI-Kiln-Thermal-Analytics"},
{id:"06",title:"AI-Based Logo Detection & Obfuscation",description:"Computer-vision research work around brand/logo detection and obfuscation in videos.",tech:["Computer Vision","Deep Learning"],categories:["Computer Vision","AI"],github:"https://github.com/kavyyyaaa/logo_detection_obfuscation"},
{id:"07",title:"AI Research Assistant",description:"RAG-based PDF question-answering assistant using Google Gemini, LangChain and FAISS for document-grounded answers.",tech:["Python","Gemini","LangChain","FAISS"],categories:["AI"],github:"https://github.com/kavyyyaaa/AI-Research-Assistant"},
{id:"08",title:"Customer Segmentation Project",description:"Customer analytics project focused on segmenting customers into meaningful groups for data-driven business insights.",tech:["Python","Pandas","Scikit-learn"],categories:["Data Analytics","Machine Learning"],github:"https://github.com/kavyyyaaa/Customer-Segmentation-Project"}
];
const featuredEl=document.getElementById("featured-projects"),allEl=document.getElementById("all-projects"),filtersEl=document.getElementById("filters");
function links(p){return `<div class="project-links"><a href="${p.github}" target="_blank" rel="noreferrer">GitHub ↗</a>${p.caseStudy?`<a href="project.html?id=${p.id}">Case study ↗</a>`:""}</div>`}
function card(p){return `<article class="project-card reveal"><div class="project-top"><span>${p.id} / 04</span><span class="project-type">${p.categories[0]}</span></div><div><h3>${p.title}</h3><p>${p.description}</p></div><div class="project-bottom"><div class="tech-list">${p.tech.map(t=>`<span>${t}</span>`).join("")}</div>${links(p)}</div></article>`}
function mini(p){return `<article class="mini-project reveal"><span class="project-number">${p.id}</span><h4>${p.title}</h4><p>${p.description}</p><div class="tech-list">${p.tech.slice(0,4).map(t=>`<span>${t}</span>`).join("")}</div>${links(p)}</article>`}
featuredEl.innerHTML=projects.filter(p=>p.featured).map(card).join("");
const more=()=>projects.filter(p=>!p.featured);
const cats=["All",...new Set(more().flatMap(p=>p.categories))];
filtersEl.innerHTML=cats.map((c,i)=>`<button class="filter ${i===0?"active":""}" data-filter="${c}">${c}</button>`).join("");
function renderAll(filter="All"){allEl.innerHTML=more().filter(p=>filter==="All"||p.categories.includes(filter)).map(mini).join("");observeReveals()}
filtersEl.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{filtersEl.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderAll(b.dataset.filter)}));
renderAll();
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");revealObserver.unobserve(e.target)}}),{threshold:.12});
function observeReveals(){document.querySelectorAll(".reveal:not(.observed)").forEach(el=>{el.classList.add("observed");revealObserver.observe(el)})}observeReveals();
const nav=document.querySelector(".nav"),menu=document.querySelector(".menu-btn");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)});document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
const intro=document.getElementById("introScreen");function closeIntro(){intro?.classList.add("is-hidden");try{sessionStorage.setItem("kavyaaIntroSeen","1")}catch(e){}}try{if(sessionStorage.getItem("kavyaaIntroSeen")==="1")intro?.classList.add("is-hidden")}catch(e){}document.getElementById("enterPortfolio")?.addEventListener("click",closeIntro);document.getElementById("skipIntro")?.addEventListener("click",closeIntro);
let ticking=false;const progress=document.getElementById("scrollProgress");window.addEventListener("scroll",()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max>0?(scrollY/max)*100:0}%`;ticking=false})},{passive:true});
// Scroll-story: one active chapter at a time, inspired by editorial portfolio storytelling.
const steps=[...document.querySelectorAll(".story-step")],storyTitle=document.getElementById("storyTitle"),storyText=document.getElementById("storyText"),storyIndex=document.getElementById("storyIndex"),storyMeter=document.getElementById("storyMeter");
const storyObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const s=e.target;steps.forEach(x=>x.classList.remove("active"));s.classList.add("active");storyTitle.textContent=s.dataset.title;storyText.textContent=s.dataset.text;storyIndex.textContent=s.dataset.index;storyMeter.style.width=`${parseInt(s.dataset.index)*33.333}%`}}),{rootMargin:"-35% 0px -45% 0px",threshold:0});steps.forEach(s=>storyObserver.observe(s));
